spring.application.name=APEEG
spring.data.mongodb.port=27017
spring.data.mongodb.database=HandOff
spring.data.mongodb.auto-index-creation=false
# 256-bit Secret Key for HMAC-SHA256 JWT Signing
app.jwt.secret=404D635166546A576E5A7234753778214125442A472D4B6150645367566B5970
# Expiration: 24 Hours in Milliseconds
app.jwt.expiration-ms=86400000
#spring.data.mongodb.port=27017

# Spring Mail Configuration for Gmail Demo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=johaibansari002@gmail.com
# IMPORTANT: Replace below with a 16-character Google App Password (not your normal password)
spring.mail.password=zlkv uyxq rvvj ghij

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Custom Application Settings
apeeg.mail.from-address=johaibansari002@gmail.com
apeeg.config.reminder-lead-days=2
apeeg.config.default-loan-days=14

# Set max file size for single uploaded image (e.g., 10MB)
spring.servlet.multipart.max-file-size=10MB

# Set max total request size (e.g., 10MB)
spring.servlet.multipart.max-request-size=10MB